- name: webservetr setup
  hosts: webservers
  tasks:
      - name: install httpd
        yum:
          name: httpd
          state: present
      - name: copy page
        template:
          src: /root/ansible/index.html
          dest: /var/www/html/index.html
        notify:
          - reloadserver
  handlers:
        - name: reloadserver
          service:
              name: httpd
              state: restarted
              
- name: haproxy setup
  hosts: proxy
  tasks:
     - name: install haproxy
       yum:
         name: haproxy
         state: present
     - name: copy haproxy config
       template:
         src: /root/ansible/haproxy.cfg
         dest: /etc/haproxy/haproxy.cfg
       notify:
         - restart_haproxy
  handlers:
        - name: restart_haproxy
          service:
             name: haproxy
             state: restarted
